#Panel
menu_panel = "🏠Меню"
category_panel = "🗂 Категории"
size_panel = "🔩 Size"
info_in_size = "ℹ️ Размеры"
brand_panel = "©️ Brand"
type_panel = "⚧ Type"
cycle_panel = "🚲 Велосипеды"
website_panel = "🌐 Веб-сайт"
info_panel = "ℹ️ Информация"
other_panel = "🧰 Другое"
back_panel = "🔙 Back"
random_panel = "🎲 Рандомное число"
