#Panel
menu_panel = "🏠 Menu"
category_panel = "🗂 Category"
size_panel = "🔩 Size"
info_in_size = "ℹ️ Размеры"
brand_panel = "©️ Brand"
type_panel = "⚧ Type"
cycle_panel = "🚲 Bikes"
website_panel = "🌐 Веб-сайт"
info_panel = "ℹ️ Information"
other_panel = "🧰 Other"
back_panel = "🔙 Back"
random_panel = "🎲 Random number"
